In [2]:
import pandas as pd
analysis_data = pd.read_csv("pff_defense_subset.csv")

In [3]:
analysis_data.head()

,Player,Position,Team,Total_Snaps,Rush_Snaps,Coverage_Snaps,Overall_Grade,Rush_Grade,Coverage_Grade,Tackles,Assists,Missed_Tackles,Sacks,Hits,Hurries,Pressures
0,Jackson Forrest,LB,DOMINION,307,136,56,84.7,63.5,56.5,25,9,7,16,6,1,23
1,Sahir West,ED,JAMES MAD,562,228,331,80.5,76.8,80.3,24,10,3,34,9,5,48
2,Jordan Mack,DI,COAST CAR,206,100,106,74.8,62.6,59.2,7,4,2,17,1,3,21
3,Bryce Deas,LB,AUBURN,185,87,26,74.3,71.2,55.2,10,5,4,8,0,3,11
4,Emmett Laws,DI,VA TECH,161,81,80,72.3,64.2,60.6,7,3,2,6,2,0,8

In [4]:
analysis_data.columns

Index(['Player', 'Position', 'Team', 'Total_Snaps', 'Rush_Snaps',
       'Coverage_Snaps', 'Overall_Grade', 'Rush_Grade', 'Coverage_Grade',
       'Tackles', 'Assists', 'Missed_Tackles', 'Sacks', 'Hits', 'Hurries',
       'Pressures'],
      dtype='object')

Subsetting by grades and stats

In [6]:
analysis_grades = analysis_data[["Player", "Position", "Overall_Grade", "Rush_Grade", "Coverage_Grade"]]
analysis_stats_raw = analysis_data[["Player", "Position", "Total_Snaps", "Tackles", "Assists", "Missed_Tackles", "Sacks", "Hits", "Hurries", "Pressures"]]

Adding in metrics relative to production (already factored into grades)

In [15]:
# calculating stats per snap
analysis_stats_normalized = analysis_stats_raw.copy()
for stat in ["Tackles", "Assists", "Missed_Tackles", "Sacks", "Hits", "Hurries", "Pressures"]:
    analysis_stats_normalized[f"{stat}_per_100_snaps"] = round(analysis_stats_normalized[stat] * 100 / analysis_stats_normalized["Total_Snaps"], 3)

In [16]:
analysis_stats_normalized.head()

,Player,Position,Total_Snaps,Tackles,Assists,Missed_Tackles,Sacks,Hits,Hurries,Pressures,Tackles_per_100_snaps,Assists_per_100_snaps,Missed_Tackles_per_100_snaps,Sacks_per_100_snaps,Hits_per_100_snaps,Hurries_per_100_snaps,Pressures_per_100_snaps
0,Jackson Forrest,LB,307,25,9,7,16,6,1,23,8.143,2.932,2.280,5.212,1.954,0.326,7.492
1,Sahir West,ED,562,24,10,3,34,9,5,48,4.270,1.779,0.534,6.050,1.601,0.890,8.541
2,Jordan Mack,DI,206,7,4,2,17,1,3,21,3.398,1.942,0.971,8.252,0.485,1.456,10.194
3,Bryce Deas,LB,185,10,5,4,8,0,3,11,5.405,2.703,2.162,4.324,0.000,1.622,5.946
4,Emmett Laws,DI,161,7,3,2,6,2,0,8,4.348,1.863,1.242,3.727,1.242,0.000,4.969